Make crio-lxc working with kubernetes
lxc/crio-lxc pull request #23
Opened 2020-07-24 07:38 UTC by r10r

Hi crio-lxc devs,

I've made a lot of changes to the crio-lxc source to make it running with kubernetes.
With my changes I can bootstrap a single node kubernetes. I have deployed several apps,
even with more complex startup commands (spec.Process.Args). 

Short background:  At my company we are currently running our monolitic system as a lxc container and we want
to take advantage of kubernetes features - so we are willing to contribute to crio-lxc in the future.

Please take some time and have a look at the changes I made and let's start discussion.

Greeting,
Ruben

My system setup:

root@container-node:~/crio-lxc# crio --version
crio version 1.19.0-dev
Version:       1.19.0-dev
GitCommit:     a7b54a80cb5f4818b2175e31fe44a84f6755a5cd
GitTreeState:  clean
BuildDate:     2020-07-16T11:23:53Z
GoVersion:     go1.14.4
Compiler:      gc
Platform:      linux/amd64
Linkmode:      dynamic

```
lxc 4.0.2
root@container-node:~/crio-lxc# lxc-checkconfig 
Kernel configuration not found at /proc/config.gz; searching...
Kernel configuration found at /boot/config-5.7.0-1-amd64
--- Namespaces ---
Namespaces: enabled
Utsname namespace: enabled
Ipc namespace: enabled
Pid namespace: enabled
User namespace: enabled
Network namespace: enabled

--- Control groups ---
Cgroups: enabled

Cgroup v1 mount points: 
/sys/fs/cgroup/systemd
/sys/fs/cgroup/pids
/sys/fs/cgroup/memory
/sys/fs/cgroup/net_cls,net_prio
/sys/fs/cgroup/devices
/sys/fs/cgroup/blkio
/sys/fs/cgroup/cpuset
/sys/fs/cgroup/freezer
/sys/fs/cgroup/cpu,cpuacct
/sys/fs/cgroup/perf_event
/sys/fs/cgroup/rdma

Cgroup v2 mount points: 
/sys/fs/cgroup/unified

Cgroup v1 clone_children flag: enabled
Cgroup device: enabled
Cgroup sched: enabled
Cgroup cpu account: enabled
Cgroup memory controller: enabled
Cgroup cpuset: enabled

--- Misc ---
Veth pair device: enabled, loaded
Macvlan: enabled, not loaded
Vlan: enabled, not loaded
Bridges: enabled, loaded
Advanced netfilter: enabled, loaded
CONFIG_NF_NAT_IPV4: missing
CONFIG_NF_NAT_IPV6: missing
CONFIG_IP_NF_TARGET_MASQUERADE: enabled, not loaded
CONFIG_IP6_NF_TARGET_MASQUERADE: enabled, not loaded
CONFIG_NETFILTER_XT_TARGET_CHECKSUM: enabled, loaded
CONFIG_NETFILTER_XT_MATCH_COMMENT: enabled, loaded
FUSE (for use with lxcfs): enabled, loaded

--- Checkpoint/Restore ---
checkpoint restore: enabled
CONFIG_FHANDLE: enabled
CONFIG_EVENTFD: enabled
CONFIG_EPOLL: enabled
CONFIG_UNIX_DIAG: enabled
CONFIG_INET_DIAG: enabled
CONFIG_PACKET_DIAG: enabled
CONFIG_NETLINK_DIAG: enabled
File capabilities: 

Note : Before booting a new kernel, you can check its configuration
usage : CONFIG=/path/to/config /usr/bin/lxc-checkconfig
```

2020-09-02 07:55 UTC, brauner commented
@hallyn Is this something that one of your people can review? :)

2020-09-02 10:03 UTC, r10r commented
@brauner I'm currently working on script to bootstrap a kubernetes single node/cluster based on debian buster with crio-lxc  I'll release it soon - this will make a test setup fairly easy for anyone willing to test/review.  

With the latest crio-lxc version the sonobuoy conformance are running against a setup with kubernetes 1.19 have currently 6 failures out of 303 tests.

2020-09-02 10:09 UTC, brauner commented
> @brauner I'm currently working on script to bootstrap a kubernetes single node/cluster based on debian buster with crio-lxc I'll release it soon - this will make a test setup fairly easy for anyone willing to test/review.
> 
> With the latest crio-lxc version the sonobuoy conformance are running against a setup with kubernetes 1.19 have currently 6 failures out of 303 tests.

Very impressive. :)

2020-09-04 07:24 UTC, hallyn commented
> @hallyn Is this something that one of your people can review? :)

Thanks for this @r10r !

@brauner - yeah,  thanks - @mikemccracken had mentioned having a few questions, but I think he's been a bit swamped.  I made a note to look through a bit myself tomorrow.

2020-09-11 18:01 UTC, hallyn requested changes
Note to self - I'm stopping at "Fix mounts on /var/run" .  will pick up from there later.

2020-09-11 18:01 UTC, hallyn commented on cmd/create.go
> +			dest = strings.TrimPrefix(dest, "/var")
Hm, how can we do this more generically, without going to the trouble of chrooting into the container rootfs and doing a readlink...   @brauner any suggestions?

2020-09-16 04:53 UTC, hallyn commented
This would be much easier to review if the commits which are overwritten by later commits were squashed.

If you have time to do that, I'll wait and re-review.

If not, then I'll let @mikemccracken speak up before I merge it.  Mike if you don't have time that's fine, I just don't want to step on your toes and merge if you had pending review comments.

2020-09-16 08:48 UTC, r10r commented
@hallyn Sorry for the delay, I'm currently setting up a prototype for our k8s cluster and still have a few fixes/changes for crio-lxc in the pipeline.  I'll try to squash the commits together for a better review.  I'll then force pull the changes to the master branch - is that ok?

2020-09-16 10:00 UTC, brauner commented on cmd/create.go
> +			dest = strings.TrimPrefix(dest, "/var")
What is this trying to do in the first place, i.e. why is this stripping `/var`?

2020-09-16 10:17 UTC, r10r commented on cmd/create.go
> +			dest = strings.TrimPrefix(dest, "/var")
This is an bugfix get containers started. /var/run "almost" always symlinks to /run and therefore lxc symlink protection kicks in and refuses the mount. I've implemented proper path resolution later on https://github.com/Drachenfels-GmbH/crio-lxc/blob/d5146786d316e4a1b28d540d3a6b78ffc18d5cb8/cmd/utils.go#L127 
As @hallyn proposed I'll squash my commits to make the review much easier.

2020-10-09 20:14 UTC, hallyn commented
> @hallyn Sorry for the delay, I'm currently setting up a prototype for our k8s cluster and still have a few fixes/changes for crio-lxc in the pipeline. I'll try to squash the commits together for a better review. I'll then force pull the changes to the master branch - is that ok?

Please let me know when you've done that :)

2020-11-16 09:10 UTC, vrubiolo commented
Just a note to mention that I am interested in those changes as well as I am evaluating using k8s w/ crio-lxc (also to evaluate migrating our application :). Thanks for doing the changes @r10r !

2020-11-16 10:49 UTC, r10r commented
Hi @vrubiolo I have a single pending issue with k8s initialization which I want to solve prior to release.
Expect a release within this week (hopefully within the next two days). 
Can you tell me what distro  you use?  I'm currently testing with debian and archlinux.

2020-11-16 10:59 UTC, vrubiolo commented
Hi @r10r and thanks for the quick reply ! For the distro, are you asking about which distro is running on the k8s node?

Right now, I don't have a dedicated k8s cluster, I am currently using minikube 1.15.0 on Fedora32. When enabling `cri-o` as the runtime, this uses the Docker driver and an Ubuntu 20.04.1 container into which k8s runs

2020-11-19 14:47 UTC, r10r commented
> Hi @r10r and thanks for the quick reply ! For the distro, are you asking about which distro is running on the k8s node?
> 
> Right now, I don't have a dedicated k8s cluster, I am currently using minikube 1.15.0 on Fedora32. When enabling `cri-o` as the runtime, this uses the Docker driver and an Ubuntu 20.04.1 container into which k8s runs

Ok that's good to know. You can help me adapting the deployment script for fedora.

2020-11-19 14:56 UTC, vrubiolo commented
> Ok that's good to know. You can help me adapting the deployment script for fedora.

Yes, I'd be glad to !

Btw, if you have an idea about #24 , I'd be most grateful :)

2020-11-19 14:58 UTC, r10r commented
> > Ok that's good to know. You can help me adapting the deployment script for fedora.
> 
> Yes, I'd be glad to !
> 
> Btw, if you have an idea about #24 , I'd be most grateful :)

I'll suggest you to wait until tomorrow. There is lot that either doesn't work or is broken in the current version. I'll release tomorrow and you can test again. I'm sure this is already fixed in my version.

2020-11-19 15:10 UTC, vrubiolo commented
> I'll suggest you to wait until tomorrow. There is a lot that either doesn't work or is broken in the current version. I'll release tomorrow and you can test again. I'm sure this is already fixed in my version.

Fantastic! Iooking forward to the release then :+1:

2020-11-20 15:53 UTC, r10r commented
@vrubiolo You can try to bootstrap your system with the files from https://gist.github.com/r10r/c6c7f43ed85bdcd37fc082b0214c7c6f 
It may contain errors, because I simply copied it from my deployment script. 
Maybe I'll turn this into a separate git repository. 
It will take still an hour or two for the release ;)

2020-12-18 09:35 UTC, vrubiolo commented
Hi @r10r , did you get more feedback on your PR? 
I should be able to get back to this in the coming weeks if all goes well (I need to look into building OCI images first)

2020-12-18 10:14 UTC, r10r commented
@vrubiolo not yet.  But shame on me - I didn't update the pull request yet.
I did quite a lot of testing and refactoring within the last weeks and I think it was worth it.
Currently I've a single outstanding issue to resolve, which I'm now able to reproduce.
I'm very confident to resolve this before next week.
Just ping me If you don't hear anything.

2020-12-18 10:30 UTC, vrubiolo commented
> Just ping me If you don't hear anything.
@r10r : thanks for the update, glad to see things are moving on your end. I'll definitely ping you !

2020-12-21 06:47 UTC, r10r commented
Sonobuoy conformance tests are now looping for 2 days successfully on our test clusters.
Please read through the README.md to get an overview of the changes.

I invite everybody to try out our dev branch https://github.com/Drachenfels-GmbH/crio-lxc/tree/v0.9.4

2020-12-21 07:24 UTC, r10r commented
@brauner @hallyn  I'm really exited about your feedback. Please try out version v0.9.4. I consider it pre-production ready.

I've done a lot of refactoring lately to improve the structure and design. And I think it was really worth it.
But it lead to a lot of merge commits which are hard to follow. I tried to squash commits more than once - but honestly, it currently takes to much precious time to clean up my commit mess. Commit history is currently still not suited for review. 

But since my desire to refactor is satisfied :D - we should get review started.
My idea is to simply squash everything together and create a single commit for review. What do you think?

@brauner I consider certain parts (cmd/init/crio-lxc-init.c, cmd/start/crio-lxc-start.c, cmd/container-hook/hook.c) for inclusion in lxc itself. Please let me know what you think about it.

2020-12-21 08:27 UTC, r10r commented
@vrubiolo Please report any issues to https://github.com/Drachenfels-GmbH/crio-lxc until merge is complete. Thanks!

2021-01-20 21:56 UTC, vrubiolo commented
Hi @r10r , just a note that I am back on this and now looking/using your fork at https://github.com/Drachenfels-GmbH/crio-lxc instead.
Thanks for all the changes you put in to allow k8s, it looks like the project was quite far from enabling it fully given all the commits you added...

2021-03-23 23:12 UTC, r10r commented
I'll close this pull request now, since my fork is now a complete rewrite and shares very little code with crio-lxc.
I renamed the project to [**lxcri**](https://github.com/drachenfels-de/lxcri) for a clear distinction between the projects.

The project has still some rough edges and had to endure my refactorings.
With liblxc from master sonobuoy conformance tests are now passing 100%. 
A public API is in progress, but is currently missing documentation and examples.
I'll release docker images soon - so anyone who wants to try out a kubernetes cluster
backed by liblxc should have look at it.

2021-03-23 23:12 UTC, closed without merging